name: 🧪 Add / Improve Test Case
description: Improve Documentation
title: "test: "
labels: ["test case", "🕵🏼‍♂️ goal: improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation update template!
  - type: textarea
    id: improve-test
    attributes:
      label: describe the test case you want to add / improve
      description: add / improve test case
      placeholder: explain it in brief
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots (if any)
      description: Add screenshots to see the demo
      placeholder: Add screenshots
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct